Repository Team-SoFa/SoFa-server, pull requests merged in 2024-12, with the labels that each got.

#28 Feat: Health Check
  src/main/java/com/sw19/sofa/domain/healthCheck/api/HealthCheckApi.java
  src/main/java/com/sw19/sofa/domain/healthCheck/controller/HealthController.java
Labels: 💫 feature

#23 Feat/#17 basic setting
  src/main/java/com/sw19/sofa/domain/auth/service/GoogleOAuth2Service.java
  src/main/java/com/sw19/sofa/domain/folder/service/FolderMangeService.java
  src/main/java/com/sw19/sofa/domain/folder/service/FolderService.java
  src/main/java/com/sw19/sofa/domain/member/service/MemberService.java
  src/main/java/com/sw19/sofa/domain/recycleBin/service/RecycleBinManageService.java
  src/main/java/com/sw19/sofa/domain/setting/api/SettingApi.java
  src/main/java/com/sw19/sofa/domain/setting/controller/SettingController.java
  src/main/java/com/sw19/sofa/domain/setting/dto/request/ToggleAlarmRequest.java
  src/main/java/com/sw19/sofa/domain/setting/dto/response/SettingResponse.java
  src/main/java/com/sw19/sofa/domain/setting/entity/Setting.java
  src/main/java/com/sw19/sofa/domain/setting/enums/AlarmType.java
  src/main/java/com/sw19/sofa/domain/setting/error/SettingErrorCode.java
  src/main/java/com/sw19/sofa/domain/setting/repository/SettingRepository.java
  src/main/java/com/sw19/sofa/domain/setting/service/SettingService.java
Labels: 💫 feature

#30 Feat: 임시 로그인 및 회원가입
  src/main/java/com/sw19/sofa/domain/auth/api/OAuthApi.java
  src/main/java/com/sw19/sofa/domain/auth/controller/OAuth2Controller.java
  src/main/java/com/sw19/sofa/domain/auth/dto/request/LoginAndSignUpReq.java
  src/main/java/com/sw19/sofa/domain/auth/service/GoogleOAuth2Service.java
Labels: 💫 feature

#34 Bug: Cors Error
  src/main/java/com/sw19/sofa/security/config/CorsConfig.java
  src/main/java/com/sw19/sofa/security/config/SecurityConfig.java
Labels: 🐛 bug

#24 Feat/#20 remind
  src/main/java/com/sw19/sofa/domain/linkcard/api/LinkCardApi.java
  src/main/java/com/sw19/sofa/domain/linkcard/controller/LinkCardController.java
  src/main/java/com/sw19/sofa/domain/linkcard/entity/LinkCard.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardMangeService.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardService.java
  src/main/java/com/sw19/sofa/domain/remind/api/RemindApi.java
  src/main/java/com/sw19/sofa/domain/remind/controller/RemindController.java
  src/main/java/com/sw19/sofa/domain/remind/dto/response/RemindRes.java
  src/main/java/com/sw19/sofa/domain/remind/entity/Remind.java
  src/main/java/com/sw19/sofa/domain/remind/enums/RemindSortBy.java
  src/main/java/com/sw19/sofa/domain/remind/repository/RemindCustomRepository.java
  src/main/java/com/sw19/sofa/domain/remind/repository/RemindCustomRepositoryImpl.java
  src/main/java/com/sw19/sofa/domain/remind/repository/RemindRepository.java
  src/main/java/com/sw19/sofa/domain/remind/service/RemindManageService.java
  src/main/java/com/sw19/sofa/domain/remind/service/RemindService.java
  src/main/java/com/sw19/sofa/global/common/entity/BaseTimeEntity.java
Labels: 💫 feature

#31 Feat: 알림 API
  src/main/java/com/sw19/sofa/domain/alarm/api/AlarmApi.java
  src/main/java/com/sw19/sofa/domain/alarm/controller/AlarmController.java
  src/main/java/com/sw19/sofa/domain/alarm/dto/response/AlarmListRes.java
  src/main/java/com/sw19/sofa/domain/alarm/dto/response/AlarmRes.java
  src/main/java/com/sw19/sofa/domain/alarm/entity/Alarm.java
  src/main/java/com/sw19/sofa/domain/alarm/enums/AlarmType.java
  src/main/java/com/sw19/sofa/domain/alarm/error/AlarmErrorCode.java
  src/main/java/com/sw19/sofa/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/sw19/sofa/domain/alarm/service/AlarmService.java
Labels: 💫 feature

#21 Feat/#10 search box
  build.gradle
  src/main/java/com/sw19/sofa/SofaApplication.java
  src/main/java/com/sw19/sofa/domain/auth/config/GoogleOAuth2Config.java
  src/main/java/com/sw19/sofa/domain/auth/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/sw19/sofa/domain/auth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/sw19/sofa/domain/auth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/sw19/sofa/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/sw19/sofa/domain/auth/service/GoogleOAuth2Service.java
  src/main/java/com/sw19/sofa/domain/folder/error/FolderErrorCode.java
  src/main/java/com/sw19/sofa/domain/folder/service/FolderService.java
  src/main/java/com/sw19/sofa/domain/linkcard/entity/LinkCardTag.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardTagService.java
  src/main/java/com/sw19/sofa/domain/member/controller/MemberController.java
  src/main/java/com/sw19/sofa/domain/searchbox/api/SearchBoxApi.java
  src/main/java/com/sw19/sofa/domain/searchbox/controller/SearchBoxController.java
  src/main/java/com/sw19/sofa/domain/searchbox/dto/response/SearchBoxRes.java
  src/main/java/com/sw19/sofa/domain/searchbox/enums/SearchBoxSortBy.java
  src/main/java/com/sw19/sofa/domain/searchbox/error/SearchBoxErrorCode.java
  src/main/java/com/sw19/sofa/domain/searchbox/repository/SearchBoxCustomRepository.java
  src/main/java/com/sw19/sofa/domain/searchbox/repository/SearchBoxCustomRepositoryImpl.java
  src/main/java/com/sw19/sofa/domain/searchbox/repository/SearchBoxRepository.java
  src/main/java/com/sw19/sofa/domain/searchbox/service/SearchBoxService.java
  src/main/java/com/sw19/sofa/domain/searchbox/service/SearchHistoryService.java
  src/main/java/com/sw19/sofa/domain/tag/api/CustomTagApi.java
  src/main/java/com/sw19/sofa/domain/tag/api/TagApi.java
  src/main/java/com/sw19/sofa/domain/tag/controller/CustomTagController.java
  src/main/java/com/sw19/sofa/domain/tag/controller/TagController.java
  src/main/java/com/sw19/sofa/domain/tag/dto/request/CustomTagReq.java
  src/main/java/com/sw19/sofa/domain/tag/dto/response/CustomTagRes.java
  src/main/java/com/sw19/sofa/domain/tag/dto/response/TagRes.java
  src/main/java/com/sw19/sofa/domain/tag/dto/response/TagSearchRes.java
  src/main/java/com/sw19/sofa/domain/tag/entity/CustomTag.java
  src/main/java/com/sw19/sofa/domain/tag/entity/Tag.java
  src/main/java/com/sw19/sofa/domain/tag/error/TagErrorCode.java
  src/main/java/com/sw19/sofa/domain/tag/repository/CustomTagRepository.java
  src/main/java/com/sw19/sofa/domain/tag/repository/TagRepository.java
  src/main/java/com/sw19/sofa/domain/tag/service/CustomTagService.java
  src/main/java/com/sw19/sofa/domain/tag/service/ManageTagService.java
  src/main/java/com/sw19/sofa/domain/tag/service/TagService.java
  src/main/java/com/sw19/sofa/global/common/dto/enums/SortOrder.java
  src/main/java/com/sw19/sofa/global/error/code/CommonErrorCode.java
  src/main/java/com/sw19/sofa/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/sw19/sofa/infra/redis/constants/RedisPrefix.java
  src/main/java/com/sw19/sofa/security/config/SecurityConfig.java
  src/main/java/com/sw19/sofa/security/entity/CustomMemberDetail.java
  src/main/java/com/sw19/sofa/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/sw19/sofa/security/jwt/provider/JwtTokenProvider.java
  src/main/resources/application.properties
Labels: 💫 feature

#26 Bug/#25 google login error
  src/main/java/com/sw19/sofa/SofaApplication.java
  src/main/java/com/sw19/sofa/domain/auth/api/OAuthApi.java
  src/main/java/com/sw19/sofa/domain/auth/controller/OAuth2Controller.java
  src/main/java/com/sw19/sofa/domain/auth/dto/CustomOAuth2User.java
  src/main/java/com/sw19/sofa/domain/auth/dto/request/GoogleLoginRequest.java
  src/main/java/com/sw19/sofa/domain/auth/service/GoogleOAuth2Service.java
  src/main/java/com/sw19/sofa/security/config/SecurityConfig.java
  src/main/java/com/sw19/sofa/security/entity/CustomMemberDetail.java
Labels: 🐛 bug

#52 [BUG] 휴지통 영구 삭제 API 오류
  src/main/java/com/sw19/sofa/domain/linkcard/repository/LinkCardTagRepository.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardTagService.java
  src/main/java/com/sw19/sofa/domain/recycleBin/service/RecycleBinManageService.java
  src/main/java/com/sw19/sofa/domain/tag/controller/CustomTagController.java
  src/main/java/com/sw19/sofa/domain/tag/controller/TagController.java
Labels: 🐛 bug

#58 [Fix] FolderListRes 오타 수정
  src/main/java/com/sw19/sofa/domain/folder/dto/response/FolderListRes.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardMangeService.java
Labels: 🐛 bug

#55 [Feat] AI 기능 구현
  build.gradle
  src/main/java/com/sw19/sofa/domain/ai/controller/AiSummaryController.java
  src/main/java/com/sw19/sofa/domain/ai/dto/request/ChatGPTRequest.java
  src/main/java/com/sw19/sofa/domain/ai/dto/response/ChatGPTResponse.java
  src/main/java/com/sw19/sofa/domain/ai/service/AiFolderService.java
  src/main/java/com/sw19/sofa/domain/ai/service/AiManageService.java
  src/main/java/com/sw19/sofa/domain/ai/service/AiService.java
  src/main/java/com/sw19/sofa/domain/ai/service/AiSummaryService.java
  src/main/java/com/sw19/sofa/domain/ai/service/AiTagService.java
  src/main/java/com/sw19/sofa/domain/ai/service/AiTitleService.java
  src/main/java/com/sw19/sofa/domain/ai/service/OpenAiService.java
  src/main/java/com/sw19/sofa/domain/ai/service/WebScrapingService.java
  src/main/java/com/sw19/sofa/domain/article/entity/Article.java
  src/main/java/com/sw19/sofa/domain/article/service/ArticleService.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardMangeService.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardTagService.java
  src/main/java/com/sw19/sofa/domain/tag/service/TagService.java
  src/main/java/com/sw19/sofa/global/common/constants/Constants.java
  src/main/java/com/sw19/sofa/global/common/dto/AiMessageDto.java
  src/main/java/com/sw19/sofa/global/config/OpenAIConfig.java
Labels: 💫 feature

#65 [Refactor] Swagger 수정
  src/main/java/com/sw19/sofa/domain/auth/dto/request/LoginAndSignUpReq.java
  src/main/java/com/sw19/sofa/domain/linkcard/dto/LinkCardTagSimpleDto.java
  src/main/java/com/sw19/sofa/domain/linkcard/dto/LinkCardTagSimpleEncryptDto.java
Labels: 📝 documentation

#66 [Fix] 전체 검색 오류
  src/main/java/com/sw19/sofa/domain/folder/service/FolderService.java
  src/main/java/com/sw19/sofa/domain/searchbox/service/SearchBoxService.java
Labels: 🐛 bug

#59 [Feat] 유저별 저장소/홈 페이지 API 구현
  src/main/java/com/sw19/sofa/domain/article/api/ArticleApi.java
  src/main/java/com/sw19/sofa/domain/article/controller/ArticleController.java
  src/main/java/com/sw19/sofa/domain/article/dto/response/ArticleRes.java
  src/main/java/com/sw19/sofa/domain/article/service/ArticleMangeService.java
  src/main/java/com/sw19/sofa/domain/article/service/ArticleService.java
  src/main/java/com/sw19/sofa/domain/article/service/ArticleTagService.java
  src/main/java/com/sw19/sofa/domain/linkcard/api/LinkCardApi.java
  src/main/java/com/sw19/sofa/domain/linkcard/controller/LinkCardController.java
  src/main/java/com/sw19/sofa/domain/linkcard/dto/response/MostTagLinkCardListRes.java
  src/main/java/com/sw19/sofa/domain/linkcard/repository/LinkCardCustomRepository.java
  src/main/java/com/sw19/sofa/domain/linkcard/repository/LinkCardCustomRepositoryImpl.java
  src/main/java/com/sw19/sofa/domain/linkcard/repository/LinkCardTagCustomRepository.java
  src/main/java/com/sw19/sofa/domain/linkcard/repository/LinkCardTagCustomRepositoryImpl.java
  src/main/java/com/sw19/sofa/domain/linkcard/repository/LinkCardTagRepository.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardMangeService.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardService.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardTagService.java
  src/main/java/com/sw19/sofa/domain/member/api/MemberApi.java
  src/main/java/com/sw19/sofa/domain/member/controller/MemberController.java
  src/main/java/com/sw19/sofa/domain/member/dto/response/MemberRes.java
  src/main/java/com/sw19/sofa/domain/recycleBin/api/RecycleBinApi.java
  src/main/java/com/sw19/sofa/domain/tag/service/CustomTagService.java
  src/main/java/com/sw19/sofa/domain/tag/service/TagService.java
  src/main/java/com/sw19/sofa/global/common/dto/ListRes.java
Labels: 💫 feature

#67 [Feat] url image
  src/main/java/com/sw19/sofa/domain/article/service/ArticleService.java
  src/main/java/com/sw19/sofa/domain/linkcard/api/LinkCardApi.java
  src/main/java/com/sw19/sofa/domain/linkcard/dto/request/CreateLinkCardBasicInfoReq.java
  src/main/java/com/sw19/sofa/domain/linkcard/dto/response/CreateLinkCardBasicInfoRes.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardMangeService.java
  src/main/java/com/sw19/sofa/global/util/ImageExtractor.java
Labels: 💫 feature

#70 [Bug] 신규 URL AI 요청 시 오류 발생
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardMangeService.java
  src/main/java/com/sw19/sofa/domain/tag/service/TagService.java
Labels: 🐛 bug

#72 [Bug] 링크카드 태그 추가 오류
  src/main/java/com/sw19/sofa/domain/linkcard/dto/request/LinkCardTagListReq.java
  src/main/java/com/sw19/sofa/domain/linkcard/service/LinkCardMangeService.java
Labels: 🐛 bug

#68 [Feat] 검색 기록 삭제
  src/main/java/com/sw19/sofa/domain/searchbox/api/SearchBoxApi.java
  src/main/java/com/sw19/sofa/domain/searchbox/controller/SearchBoxController.java
  src/main/java/com/sw19/sofa/domain/searchbox/service/SearchHistoryService.java
  src/main/java/com/sw19/sofa/global/common/constants/Constants.java
Labels: 💫 feature

#74 [Fix] Refresh token exp 시간 오류
  src/main/java/com/sw19/sofa/domain/auth/service/GoogleOAuth2Service.java
  src/main/java/com/sw19/sofa/security/jwt/error/code/JwtErrorCode.java
  src/main/java/com/sw19/sofa/security/jwt/provider/JwtTokenProvider.java
Labels: 🐛 bug
